# Generated by Django 3.0.6 on 2020-06-04 08:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('words', '0003_auto_20200603_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='key',
            name='word',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='key',
            unique_together={('user', 'word')},
        ),
    ]
