# Generated by Django 3.0.6 on 2020-06-04 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0004_auto_20200604_0823'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=300)),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='words.Key')),
            ],
        ),
    ]
