# Generated by Django 3.0.6 on 2020-06-16 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0006_video_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='creation_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
